### ISSUE TITLE
A user should be able to navigate to their cart regardless of login status

### ISSUE THREAD

**Issue by cardeljan** [the-fellowship-1804/fellowship-of-shoppers#13]

**Comment by SpencerWhitehead7** [comment]
Also, they should be able to check the cart out without logging in. You wouldn't be able to pre-populate their address/payment info or add anything to the database (like User OrderHistory), but it should still take the payment and clear the cart on the store-state.

**Comment by SpencerWhitehead7** [comment]
Additionally, if the user is not logged in, adds some stuff to the cart, and then logs in, the cart property on the User model should have the items from the store-state cart pushed in, and the store-state cart should update automatically to include all the user's cart items (that last part might already happen automatically when you log in).

I think the best place to do this is in the login-event function, although as I haven't done much authentication stuff, I'm not sure.

You will probably have to make a new redux thunk to merge the store-state cart and the user-model cart. I don't think the current thunks allow you to alter more than one item at a time and modifying them so they do would be a nightmare.

**Comment by SpencerWhitehead7** [comment]
the DK team did it!
