### ISSUE TITLE
Hitting checkout on cart should bring user to a checkout page, where they can input payment info/addresses etc.

### ISSUE THREAD

**Issue by cardeljan** [the-fellowship-1804/fellowship-of-shoppers#16]

**Comment by SpencerWhitehead7** [comment]
The checkout page should be prepopulated with their account's saved address and payment info if it exists, with the option to change them on the page. We should try to use stripe to process/validate their payment.

When they submit their order, their cart should be unshifted into their orderHistory in the DB, then the cart should be reset to an empty array. The user should have their store-state cart reset to an empty array as well.

**Comment by SpencerWhitehead7** [comment]
We did it!
