### ISSUE TITLE
A user should be able to see an account page, and edit their payment info, shipping address etc.

### ISSUE THREAD

**Issue by cardeljan** [the-fellowship-1804/fellowship-of-shoppers#17]

**Comment by SpencerWhitehead7** [comment]
The edit user page should be a form where they can edit their account information. Submitting the form should make a DB request that updates their information then redirects them to the SingleUser page.

The user should be automatically redirected to this page after they successfully create an account.
They should also be able to access this page by clicking a button on their personal SingleUser page.

**Comment by SpencerWhitehead7** [comment]
Little DK did it!
